import { aboutType } from "./aboutType"
import { rentalType } from "./rentalType"
import { accomodationType } from "./accomodationType"
import { courseType } from "./courseType"
import { reviewType } from "./reviewType"
import { divesiteType } from "./divesiteType"
import { serviceType } from "./serviceType"
import { contactType } from "./contactType"
import { homeType } from "./homeType"
import { diveType } from "./diveType"
export const schemaTypes = [aboutType, rentalType, accomodationType, courseType, reviewType, divesiteType, serviceType, contactType, homeType, diveType]
